### PR TITLE
Ajc/expandedlearning events

### PR DESCRIPTION
**Pull request by AlexCano21**
Integrated the expanded learning logo by placing it in a row with the heading of the jumbotron. Added the tedx youth and film festival cards by making markdown files which are called in the expanded learning page.

### CODE REVIEW

**Comment by AlexCano21** [comment]
Added resolutions to image file names

**Comment by AlexCano21** [comment]
2. Changed subtitles of the cards to "Coming Spring 2019 
3. Spelling problems fixed
4. Made cards the same size by utilizing the flex feature. All of the cards have a "align-items-stretch" to make all the cards the same height as the others in the row.

**Comment by ipnicholson** [comment]
>     4. Made cards the same size by utilizing the flex feature. All of the cards have a "align-items-stretch" to make all the cards the same height as the others in the row.

Nice use of align-items-stretch @AlexCano21

**Comment by AlexCano21** [comment]
1. Drafts set to false for expanded learning event cards 
2. Contacted Angela for new expanded learning logo, placeholder logo set. Added padding to the top of the "learn by doing" quote to reduce cluttered feel 
3. For events with no description newsletter information added to the content section

**Comment by ipnicholson** [comment]
Looks good, now just get the PM to sign off on it

**Pull request merged**
