### PR TITLE
Videoportfoliochanges

### PR DESCRIPTION
**Pull request by AlexCano21**
I edited the video titles and descriptions that Sam wanted. I also deleted the spring break videos and capitalized RCM in the RCMakes.

### CODE REVIEW

**Comment by AlexCano21** [comment]
I also added padding to the bottom of the video cards.

**Comment by AlexCano21** [comment]
Made spaces in the video-production archetype and deleted some front matter that we didn't need. I also changed the existing markdown files to match the archetype.

**Comment by AlexCano21** [comment]
Renamed the video production archetype to match the folder that we are using and deleted the old folder that wasn't needed.

**Comment by ipnicholson** [comment]
approved

**Pull request merged**
